/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author umam
 */
public class Pembelian extends javax.swing.JFrame {
    
    private Connection con;
    private Statement st;
    private ResultSet RSpembelian;
    private String sql="";
    JasperReport Jasrep;
    JasperPrint Jaspri;
    Map param= new HashMap();
    JasperDesign JasDes;
    private String tran, ks, np, kb, tgl;
    private int jlh, h, t;

    /**
     * Creates new form MenuUtama
     */
    public Pembelian() {
        initComponents();
        KoneksiDB();
        ShowData(sql);
        waktu();
        aktif(false);
        setTombol(true);
    }
    
    private void KoneksiDB (){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_draffa", "root", "");
            System.out.println("Koneksi Berhasil");
            //JOptionPane.showMessageDialog(null,"Berhasil");
        } catch (Exception e) {
            System.out.println("koneksi gagal \n"+e);
        }
    }
    
    private void ShowData(String sql){
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn ("No");
        data.addColumn ("No Transaksi");
        data.addColumn ("Kode Supplier");
        data.addColumn ("Nama Supplier");
        data.addColumn ("Tgl Transaksi");
        data.addColumn ("Kode Barang");
        data.addColumn ("Jumlah");
        data.addColumn ("Harga");
        data.addColumn ("Total");
        try{    
            int i = 1;
            st=con.createStatement();
            RSpembelian=st.executeQuery("select * from pembelian");
            while (RSpembelian.next())
                data.addRow(new Object[]{
                (""+i++),
                    RSpembelian.getString(1), RSpembelian.getString(2),
                    RSpembelian.getString(3), RSpembelian.getString(4),
                    RSpembelian.getString(5), RSpembelian.getString(6),
                    RSpembelian.getString(7), RSpembelian.getString(8)
                });
            tabelpembelian.setModel(data);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR \n Gagal Memuat KeDatabase \n Aktifkan Database Sebelum Memulai");
        }
    }
    
    private void Clear(){
        
        no_tran.setText("");
        kd_sup.setText("");
        nm_p.setText("");
        nm_brg.setText("");
        jmlh.setText("");
        harga.setText("");
        total.setText("");
        //tgl_tran.setDate(null);
    }
    
    public void waktu(){
        Date tgll= new Date();
        tgl_tran.setDate(tgll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        no_tran = new javax.swing.JTextField();
        kd_sup = new javax.swing.JTextField();
        nm_p = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jmlh = new javax.swing.JTextField();
        nm_brg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tgl_tran = new com.toedter.calendar.JDateChooser();
        cari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpembelian = new javax.swing.JTable();
        cetak = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 68, 68));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 221, 135));
        jLabel3.setText("DATA PEMBELIAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 221, 135));
        jLabel5.setText("Kode Suplier");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(221, 221, 135));
        jLabel7.setText("Nama Supplier");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        no_tran.setBackground(new java.awt.Color(240, 240, 176));
        no_tran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_tranActionPerformed(evt);
            }
        });
        no_tran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                no_tranKeyPressed(evt);
            }
        });
        getContentPane().add(no_tran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 181, -1));

        kd_sup.setBackground(new java.awt.Color(240, 240, 176));
        kd_sup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                kd_supFocusLost(evt);
            }
        });
        getContentPane().add(kd_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 181, -1));

        nm_p.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nm_p.setEnabled(false);
        nm_p.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nm_pFocusLost(evt);
            }
        });
        getContentPane().add(nm_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 181, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 221, 135));
        jLabel10.setText("Kode Barang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 14));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 221, 135));
        jLabel11.setText("Jumlah");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, 14));

        jmlh.setBackground(new java.awt.Color(240, 240, 176));
        jmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlhKeyReleased(evt);
            }
        });
        getContentPane().add(jmlh, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 201, -1));

        nm_brg.setBackground(new java.awt.Color(240, 240, 176));
        getContentPane().add(nm_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 201, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(221, 221, 135));
        jLabel12.setText("Harga");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, 14));

        harga.setBackground(new java.awt.Color(240, 240, 176));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 201, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 221, 135));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 14));

        total.setBackground(new java.awt.Color(240, 240, 176));
        total.setEnabled(false);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 201, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(221, 221, 135));
        jLabel9.setText("Tgl Transaksi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        tgl_tran.setBackground(new java.awt.Color(240, 240, 176));
        tgl_tran.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_tranPropertyChange(evt);
            }
        });
        getContentPane().add(tgl_tran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 132, -1));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(221, 221, 135));
        jLabel4.setText("No Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 14));

        tambah.setBackground(new java.awt.Color(255, 255, 255));
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add(2).png"))); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/garbage(1).png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 70, -1));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit(1).png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload(1).png"))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save(1).png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        tabelpembelian.setBackground(new java.awt.Color(240, 240, 176));
        tabelpembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Transaksi", "Kode Supplier", "Nama Perusahaan", "Kode Barang", "Nama Barang", "Jumlah", "Harga", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabelpembelian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 940, 120));

        cetak.setBackground(new java.awt.Color(255, 255, 255));
        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 110, 44));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(221, 221, 135));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-pattern-shadow-dark-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));

        jMenu1.setText("Home");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modify.png"))); // NOI18N
        jMenuItem1.setText("Data Barang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/People.png"))); // NOI18N
        jMenuItem2.setText("Data Supplier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Female.png"))); // NOI18N
        jMenuItem3.setText("Data Pelanggan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buy.png"))); // NOI18N
        jMenuItem5.setText("Penjualan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delivery.png"))); // NOI18N
        jMenuItem4.setText("Pembelian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Keluar");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_tranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_tranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_tranActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        
        tran=String.valueOf(no_tran.getText());
        ks=String.valueOf(kd_sup.getText());
        np=String.valueOf(nm_p.getText());
        kb=String.valueOf(nm_brg.getText());
        jlh=Integer.parseInt(jmlh.getText());
        h=Integer.parseInt(harga.getText());
        t=Integer.parseInt(total.getText());
        
        try{
            sql="INSERT INTO pembelian (kd_pembelian, kd_suplier, perusahaan, tgl, kd_barang, jumlah, harga, total)value"
                    + "('"+ tran +"','"+ ks +"','"+ np +"','"+ tgl +"','"+ kb +"','"+ jlh +"','"+ h +"','"+ t +"')";
            st=con.createStatement();
            st.execute(sql);
            Clear();
            ShowData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR \n Gagal Menyimpan Data"+e.getMessage());
        }
        
    }//GEN-LAST:event_simpanActionPerformed

    private void kd_supFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kd_supFocusLost
        // TODO add your handling code here: 
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_draffa", "root", "");
            st=con.createStatement();
            RSpembelian=st.executeQuery("select * from supplier where kd_supplier='" + kd_sup.getText() + "'");
            //ResultSet rs = st.executeQuery("SELECT * FROM servis WHERE KdSakit='" + jTextField9.getText() + "'");
           
            if (RSpembelian.next()) {
                nm_p.setText(RSpembelian.getString("nama_toko"));
            } else{
                nm_p.setText(null);
                kd_sup.setText(null);
                JOptionPane.showMessageDialog(null, "Kode Supplier Tidak Ditemukan");
            } 
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data \n Data Tidak Di Temukan"+e.getMessage());
        }
    }//GEN-LAST:event_kd_supFocusLost

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        Clear();
        aktif(false);
        setTombol(true);
    }//GEN-LAST:event_resetActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        tran=String.valueOf(no_tran.getText());
        ks=String.valueOf(kd_sup.getText());
        np=String.valueOf(nm_p.getText());
        kb=String.valueOf(nm_brg.getText());
        jlh=Integer.parseInt(jmlh.getText());
        h=Integer.parseInt(harga.getText());
        t=Integer.parseInt(total.getText());
        try{
            sql="update pembelian set kd_suplier='"+ ks +"',perusahaan='"+ np +"',tgl='"+ tgl +"',kd_barang='"+ kb +"',jumlah='"+ jlh +"',harga='"+ h +"',total='"+ t +"' where kd_pembelian = '"+ tran +"'";
            st=con.createStatement();
            st.execute(sql);
            Clear();
            ShowData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR \n"+e.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        tran=String.valueOf(no_tran.getText());
        try{
            sql="DELETE FROM pembelian"
                    +" where kd_pembelian ='"+ tran +"' ";
            st=con.createStatement();
            st.execute(sql);
            Clear();
            ShowData(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR \n"+e.getMessage());
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void jmlhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlhKeyReleased
        // TODO add your handling code here:
        String qtys=harga.getText();       
        String totals=jmlh.getText();
        double qtysd=Double.parseDouble(qtys);
        double totalsd=Double.parseDouble(totals);
        DecimalFormat df = new DecimalFormat("#.##");
        total.setText(df.format(qtysd * totalsd));
    }//GEN-LAST:event_jmlhKeyReleased

    private void nm_pFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nm_pFocusLost
        // TODO add your handling code here:
            
    }//GEN-LAST:event_nm_pFocusLost

    private void no_tranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_tranKeyPressed
        // TODO add your handling code here:
        tran=no_tran.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="SELECT * FROM pembelian "
                        +"where kd_pembelian='"+ tran +"'";
                st=con.createStatement();
                RSpembelian=st.executeQuery(sql);
                while (RSpembelian.next()){
                    kd_sup.setText(RSpembelian.getString("kd_suplier"));
                    nm_p.setText(RSpembelian.getString(3));
                    tgl_tran.setDate(RSpembelian.getDate(4));
                    nm_brg.setText(RSpembelian.getString(5));
                    harga.setText(RSpembelian.getString(6));
                    jmlh.setText(RSpembelian.getString(7));
                    total.setText(RSpembelian.getString(8));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR \n Data Tidak Ada / Tidak Ditemukan" +e.getMessage());
                //nm_brg.requestFocus();
            }
        }
        
                    
        
    }//GEN-LAST:event_no_tranKeyPressed

    private void tgl_tranPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_tranPropertyChange
        // TODO add your handling code here:
        if(tgl_tran.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tgl=format.format(tgl_tran.getDate());
        }
    }//GEN-LAST:event_tgl_tranPropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Barang brg = new Barang();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Supplier sup = new Supplier();
        sup.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Pelanggan mem = new Pelanggan();
        mem.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Penjualan pen = new Penjualan();
        pen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Pembelian pem = new Pembelian();
        pem.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        aktif(true);
        otomatis();
        setTombol(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
     String kd_pembelian = no_tran.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_draffa", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM pembelian WHERE kd_pembelian like '"+kd_pembelian+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next())
            {
                aktif(true);
                setTombol(false);
                kd_sup.setText(rs.getString(2));
                nm_p.setText(rs.getString(3));
                tgl_tran.setDate(rs.getDate(4));
                nm_brg.setText(rs.getString(5));
                harga.setText(rs.getString(6));
                jmlh.setText(rs.getString(7));
                total.setText(rs.getString(8));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }
            statement.close();
            koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_cariActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_draffa", "root", "");
            File report = new File("./src/ireport/pembelian.jrxml");
            JasDes = JRXmlLoader.load(report);
            param.clear();
            JasperReport JasRep = JasperCompileManager.compileReport(JasDes);
            JasperPrint JasPri = JasperFillManager.fillReport(JasRep, param, koneksi);
            JasperViewer.viewReport(JasPri,false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_cetakActionPerformed
 private void otomatis(){
        try {
            open_db();
            String sql="select right (kd_pembelian,2)+1 from pembelian";
            ResultSet rs=st.executeQuery(sql);
            kd_sup.setText("");
            nm_p.setText("");
            nm_brg.setText("");
            harga.setText("");
            jmlh.setText("");
            total.setText("");
            if(rs.next()){
                rs.last();
                String no=rs.getString(1);
                while (no.length()<3){
                    no="0"+no;
                    no_tran.setText("PB"+no);}
                }
            else
            {
               no_tran.setText("PB001"); 
            }
            } catch (Exception e) 
            {
        }
    }
    private void open_db() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_draffa", "root", "");
            st = (com.mysql.jdbc.Statement) con.createStatement();

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi gagal");
            System.out.println(e.getMessage());
        }
    }
    private void aktif(boolean x) {
     kd_sup.setEditable(x);
     no_tran.requestFocus();}

    private void setTombol(boolean t) {
     tambah.setEnabled(t);
     simpan.setEnabled(!t);
     hapus.setEnabled(!t);
     edit.setEnabled(!t);
     reset.setEnabled(!t);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cetak;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlh;
    private javax.swing.JTextField kd_sup;
    private javax.swing.JTextField nm_brg;
    private javax.swing.JTextField nm_p;
    private javax.swing.JTextField no_tran;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelpembelian;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tgl_tran;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
